version: "3.5"

services:
  postgres:
    container_name: postgres-studyweek
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: studyweek
    volumes:
      - .:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    restart: unless-stopped
